# master branch
[context.production]

base = "services/web/"
publish = "build"
command = "yarn run build"
[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200


# Skip build and deploy for any other branch
[context.branch-deploy]

ignore = "exit 0"
