export const states = [
  "Andaman & Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra & Nagar Haveli",
  "Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Orissa",
  "Pondicherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Tripura",
  "Uttar Pradesh",
  "Uttaranchal",
  "West Bengal",
];

export const statesObj = {
  "Andaman & Nicobar": 0,
  "Andhra Pradesh": 1,
  "Arunachal Pradesh": 2,
  Assam: 3,
  Bihar: 4,
  Chandigarh: 5,
  Chhattisgarh: 6,
  "Dadra & Nagar Haveli": 7,
  "Daman & Diu": 8,
  Delhi: 9,
  Goa: 10,
  Gujarat: 11,
  Haryana: 12,
  "Himachal Pradesh": 13,
  "Jammu & Kashmir": 14,
  Jharkhand: 15,
  Karnataka: 16,
  Kerala: 17,
  Lakshadweep: 18,
  "Madhya Pradesh": 19,
  Maharashtra: 20,
  Manipur: 21,
  Meghalaya: 22,
  Mizoram: 23,
  Nagaland: 24,
  Orissa: 25,
  Pondicherry: 26,
  Punjab: 27,
  Rajasthan: 28,
  Sikkim: 29,
  "Tamil Nadu": 30,
  Tripura: 31,
  "Uttar Pradesh": 32,
  Uttaranchal: 33,
  "West Bengal": 34,
};
