apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  TYPEORM_CONNECTION: postgres
  TYPEORM_HOST: "<DB_HOST>"
  TYPEORM_USERNAME: "<DB_USERNAME>"
  TYPEORM_PASSWORD: "<DB_PASSWORD>"
  TYPEORM_DATABASE: "<DB_NAME>"
  TYPEORM_DRIVER_EXTRA: "{\"ssl\": {\"rejectUnauthorized\": false, \"ca\": \"-----BEGIN CERTIFICATE-----<CERTIFICATE HERE>-----END CERTIFICATE-----\\n\"} }"
  # Use the following snippet to read the certificate into a variable
  # Then dump it in a file and assign it to TYPEORM_DRIVER_EXTRA.ssl.ca
  # fs.readFileSync("ca-certificate.crt").toString()
  TYPEORM_PORT: "5432"
  TYPEORM_SYNCHRONIZE: "true"
  TYPEORM_LOGGING: "true"
  TYPEORM_ENTITIES: "src/entity/*.*"
  PORT: "5000"
  REFRESH_TOKEN_SECRET: 345tertgdfgdrur6rgdb45b45
  ACCESS_TOKEN_SECRET: rhrth565675785u76tyjrtyj
  # SMTP_SERVICE: "gmail" # Only for non-custom-domain emails eg. gmail
  SMTP_IGNORE_TLS: "true"
  SMTP_HOST: "<SMTP_HOST>"
  SMTP_USER: "<SMTP_USER>"
  SMTP_PASS: "<SMTP_PASS>"
  WEB: "<WEB_URL>"
  MODEL_SERVER: "http://model-svc"
  ROOT_EMAIL: "root@blah.com"
  ROOT_PASSWORD: "12345"
